name: json_serializable_uuid_converter
description: Utilities for working with JsonSerializable
version: 1.0.0
repository: https://github.com/sbordeyne/json_utils/tree/master/packages/json_serializable_uuid_converter

environment:
  sdk: ">=3.0.0"

dependencies:
  json_annotation: ^4.9.0
  uuid: '>=4.0.0 <5.0.0'

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
