name: json_serializable_flutter_converters
description: JsonConverters for Flutter/material types
version: 1.0.0
repository: https://github.com/sbordeyne/dart_json_utils/tree/master/packages/json_serializable_flutter_converters
homepage: https://github.com/sbordeyne/dart_json_utils/tree/master/packages/json_serializable_flutter_converters
issue_tracker: "https://github.com/sbordeyne/dart_json_utils/issues"
topics:
  - json-serializable
  - flutter
  - codegen
  - converter
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.0
